server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.158.185:7776/eureka/
spring:
  application:
    name: jd-producer-pay
  redis: #Redis配置
      database: 0 # Redis数据库索引（默认为0）
      host: 127.0.0.1  #Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5
  rabbitmq:
    host: 188.131.133.118
    port: 5672
    username: sunyi
    password: 123456
    virtual-host: /sunyimq
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
  zipkin: #-ui
    base-url: http://188.131.133.118:7700
  sleuth: #追踪
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true
logging:
  level: info
