server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.158.185:7776/eureka/
spring:
  datasource:
    url: jdbc:mysql://www.lhlsy.com:3306/JD_SHOP_ORDER
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: jd-producer-order
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 1000
      min-idle: 5
  rabbitmq:
    host: 188.131.133.118
    port: 5672
    username: zhanglongfei
    password:  123456
    virtual-host: /zhanglongfeimq
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
  zipkin:
    base-url: http://188.131.133.118:7700
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
