server:
  port: 8029
spring:
  application:
    name: jd-consumer-coupon
  zipkin: #-ui
    base-url: http://188.131.133.118:7700
  sleuth: #\u8FFD\u8E2A
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.158.185:7776/eureka/
logging:
  level: info
